---
- name: be sure the Mozilla PPA is configured
  become: yes
  ansible.builtin.apt_repository:
    repo: "ppa:mozillateam/ppa"
    filename: mozilla

- name: be sure the preferences file is in place
  become: yes
  ansible.builtin.copy:
    src: mozillateam
    dest: /etc/apt/preferences.d/mozillateam

- name: be sure firefox is installed
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400
    name:
      - firefox
      - firefox-locale-de

- name: be sure Firefox uses the custom temp dir
  become: yes
  ansible.builtin.lineinfile:
    path: /usr/share/applications/firefox.desktop
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^Exec=.*firefox %u"
      line: "Exec=env TEMP=/home/{{ workstation_user }}/tmp/firefox firefox %u"
    - regexp: "^Exec=.*firefox --new-window %u"
      line: "Exec=env TEMP=/home/{{ workstation_user }}/tmp/firefox firefox --new-window %u"
    - regexp: "^Exec=.*firefox --private-window %u"
      line: "Exec=env TEMP=/home/{{ workstation_user }}/tmp/firefox firefox --private-window %u"

- name: be sure the firefox policies file is in place
  become: yes
  when: firefox_policies
  ansible.builtin.template:
    src: policies.json
    dest: /usr/lib/firefox/distribution/policies.json
    owner: root
