---
- name: be sure php packages are installed
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400
    name:
      - php-curl
      - php-xdebug

- name: be sure the phpactor config is linked
  ansible.builtin.file:
    src: ~/git/ansible-workstation/roles/php_dev/files/phpactor
    dest: ~/.config/phpactor
    state: link

- name: be sure the php module is linked
  ansible.builtin.file:
    src: ~/git/ansible-workstation/roles/php_dev/files/php.lua
    dest: ~/.config/nvim/lua/weeman/modules/php.lua
    state: link

- name: be sure the php module is registered
  ansible.builtin.lineinfile:
    path: ~/.config/nvim/lua/weeman/modules.lua
    regexp: '^  require\("weeman.modules.php"\),'
    line: '  require("weeman.modules.php"),'
    insertafter: "^return"
