---
- hosts: all
  roles:
    - role: base
      tags: [ base ]
    - role: bash
      tags: [ bash ]
    - role: fonts
      tags: [ fonts ]

    - role: ssh
      tags: [ ssh ]
    - role: ssh_config
      vars:
        ssh_env: personal
      tags: [ ssh ]
      when: specific_roles.ssh_personal is defined and specific_roles.ssh_personal
    - role: ssh_config
      vars:
        ssh_env: element
      tags: [ ssh ]
      when: specific_roles.ssh_element is defined and specific_roles.ssh_element

    - role: mumble
      tags: [ mumble ]
      when: specific_roles.mumble is defined and specific_roles.mumble
    - role: svgo
      tags: [ svgo ]
      when: specific_roles.svgo is defined and specific_roles.svgo
    - role: screenruler
      tags: [ screenruler ]
    - role: emblem
      tags: [ emblem ]
    - role: keepassxc
      when: specific_roles.keepassxc is defined and specific_roles.keepassxc
      tags: [ keepassxc ]
    - role: pick
      tags: [ pick ]
    - role: soundrecorder
      tags: [ soundrecorder ]
    - role: flameshot
      tags: [ flameshot ]
    - role: libreoffice
      tags: [ libreoffice ]
    - role: certbot
      tags: [ certbot ]
      when: specific_roles.certbot is defined and specific_roles.certbot
    - role: git
      tags: [ git ]
    - role: fzf
      tags: [ fzf ]
    - role: kitty
      tags: [ kitty ]
    - role: nodejs
      tags: [ nodejs ]
    - role: neovim
      tags: [ neovim ]
    - role: fd
      tags: [ fd ]
    - role: flatpak
      tags: [ flatpak ]
    - role: gnome
      tags: [ gnome ]
    - role: docker
      tags: [ docker ]
    - role: clamav
      tags: [ clamav ]
      when: specific_roles.clamav is defined and specific_roles.clamav

    - role: inkscape
      tags: [ inkscape ]
    - role: scribus
      tags: [ scribus ]
      when: specific_roles.scribus is defined and specific_roles.scribus
    - role: tailscale
      tags: [ tailscale ]
      when: specific_roles.tailscale is defined and specific_roles.tailscale
    - role: element-desktop
      tags: [ element-desktop ]
    - role: firefox
      tags: [ firefox ]
    - role: thunderbird
      tags: [ thunderbird ]
    - role: virtualbox
      tags: [ virtualbox ]
      when: specific_roles.virtualbox
    - role: mpv
      tags: [ mpv ]
    - role: youtubedl
      tags: [ youtubedl ]
    - role: furtherance
      tags: [ furtherance ]
    - role: chromium
      tags: [ chromium ]
    - role: peek
      tags: [ peek ]
    - role: jitsi
      tags: [ jitsi ]
    - role: break_timer
      tags: [ break_timer ]
      when: specific_roles.break_timer is defined and specific_roles.break_timer
    - role: screenkey
      tags: [ screenkey ]
    - role: regolith
      tags: [regolith]
      when: specific_roles.regolith is defined and specific_roles.regolith
    - role: rofi
      tags: [rofi]
      when: specific_roles.rofi is defined and specific_roles.rofi
    - role: pipewire
      tags: [pipewire]
      when: specific_roles.pipewire is defined and specific_roles.pipewire

    - role: python
      tags: [ python ]
    - role: php
      tags: [ php ]
    - role: js_dev
      tags: [ js_dev ]
    - role: dbeaver
      tags: [ dbeaver ]
      when: specific_roles.dbeaver is defined and specific_roles.dbeaver
    - role: reveal-md
      tags: [ reveal-md ]
      when: specific_roles.reveal_md is defined and specific_roles.reveal_md

    - role: rust_dev
      tags: [ rust_dev ]
      when: specific_roles.rust_dev is defined and specific_roles.rust_dev
    - role: cspell
      tags: [ cspell ]
    - role: arduino_dev
      tags: [ arduino_dev ]
      when: specific_roles.arduino_dev
    - role: c_dev
      tags: [ c_dev ]
      when: specific_roles.c_dev
    - role: dev_tools
      tags: [ dev_tools, dev ]
    - role: php_dev
      tags: [ php, php_dev ]
      when: specific_roles.php_dev
    - role: reuse
      tags: [ reuse ]
      when: specific_roles.reuse
    - role: poedit
      tags: [ poedit ]
      when: specific_roles is defined and specific_roles.poedit
- hosts: weeman_klapp
  roles:
    - role: fixfnkeys
      tags: [ fixfnkeys ]
- hosts: michaelw_element_klapp
  roles:
    - role: fixfnkeys
      tags: [ fixfnkeys ]
    - role: fix_bt_iwlwifi
      tags: [ fix_bt_iwlfi ]
