---
- hosts: all
  roles:
    - role: base
      tags: [ base ]
    - role: bash
      tags: [ bash ]

    - role: ssh
      tags: [ ssh ]
    - role: ssh_config
      vars:
        ssh_env: personal
      tags: [ ssh ]
      when: specific_roles.ssh_personal is defined and specific_roles.ssh_personal
    - role: ssh_config
      vars:
        ssh_env: element
      tags: [ ssh ]
      when: specific_roles.ssh_element is defined and specific_roles.ssh_element

    - role: git
      tags: [ git ]
    - role: fzf
      tags: [ fzf ]
    - role: kitty
      tags: [ kitty ]
    - role: nodejs
      tags: [ nodejs ]
    - role: neovim
      tags: [ neovim ]
    - role: fd
      tags: [ fd ]
    - role: flatpak
      tags: [ flatpak ]
    - role: gnome
      tags: [ gnome ]
    - role: docker
      tags: [ docker ]

    - role: inkscape
      tags: [ inkscape ]
    - role: element-desktop
      tags: [ element-desktop ]
    - role: firefox
      tags: [ firefox ]
    - role: thunderbird
      tags: [ thunderbird ]
    - role: virtualbox
      tags: [ virtualbox ]
      when: specific_roles.virtualbox
    - role: mpv
      tags: [ mpv ]
    - role: youtubedl
      tags: [ youtubedl ]
    - role: furtherance
      tags: [ furtherance ]
    - role: chromium
      tags: [ chromium ]
    - role: peek
      tags: [ peek ]

    - role: python
      tags: [ python ]
    - role: php
      tags: [ php ]

    - role: arduino_dev
      tags: [ arduino_dev ]
      when: specific_roles.arduino_dev
    - role: c_dev
      tags: [ c_dev ]
      when: specific_roles.c_dev
    - role: php_dev
      tags: [ php, php_dev ]
      when: specific_roles.php_dev
- hosts: weeman_klapp
  roles:
    - role: fixfnkeys
      tags: [ fixfnkeys ]
