---
- name: be sure the nvim configs are linked
  ansible.builtin.file:
    src: "~/git/ansible-workstation/roles/js_dev/files/config/{{ item }}"
    dest: "~/.config/nvim/{{ item }}"
    state: link
  with_items:
    - vsnip/js.json
    - vsnip/js_test.json

- name: be sure npm packages are installed
  community.general.npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - typescript
    - typescript-language-server
    - eslint_d
    - "@fsouza/prettierd"
    - typescript-plugin-css-modules

- name: be sure the js module is linked
  ansible.builtin.file:
    src: ~/git/ansible-workstation/roles/js_dev/files/js.lua
    dest: ~/.config/nvim/lua/weeman/modules/js.lua
    state: link

- name: be sure the js module is registered
  ansible.builtin.lineinfile:
    path: ~/.config/nvim/lua/weeman/modules.lua
    regexp: '^  require\("weeman.modules.js"\),'
    line: '  require("weeman.modules.js"),'
    insertafter: "^return"
