---
- name: be sure the nvim configs are linked
  file:
    src: "~/git/ansible-workstation/roles/js_dev/files/config/{{ item }}"
    dest: "~/.config/nvim/{{ item }}"
    state: link
  with_items:
    - vsnip/js_test.json

- name: be sure npm packages are installed
  npm:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    global: yes
  with_dict:
    typescript: "4.7.4"
    typescript-language-server: "1.1.2"

- name: be sure the js module is linked
  file:
    src: ~/git/ansible-workstation/roles/js_dev/files/js.lua
    dest: ~/.config/nvim/lua/weeman/modules/js.lua
    state: link

- name: be sure the js module is registered
  lineinfile:
    path: ~/.config/nvim/lua/weeman/modules.lua
    regexp: '^  require\("weeman.modules.js"\),'
    line: '  require("weeman.modules.js"),'
    insertafter: "^return"
