---
- name: Be sure the nodejs repo signing key is installed
  become: yes
  ansible.builtin.apt_key:
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Be sure the nodejs repo is configured
  become: yes
  ansible.builtin.apt_repository:
    repo: deb https://deb.nodesource.com/node_20.x jammy main
    filename: nodejs

- name: Be sure npmrc is linked
  ansible.builtin.file:
    src: ~/git/ansible-workstation/roles/nodejs/files/.npmrc
    dest: ~/.npmrc
    state: link

- name: Be sure nodejs is installed
  become: yes
  ansible.builtin.apt:
    name: nodejs

- name: Be sure yarn is installed
  community.general.npm:
    name: yarn
    global: yes
