---
- name: be sure the .ssh dir exists
  file:
    path: ~/.ssh/config.d
    mode: "700"
    state: directory
    recurse: yes

- name: be sure the ssh config is linked
  file:
    src: "~/git/ansible-workstation/roles/ssh/files/config"
    dest: ~/.ssh/config
    state: link
