---
- name: be sure the regolith apt signing key is installed
  become: yes
  apt_key:
    url: https://regolith-desktop.org/regolith.key
    state: present

- name: be sure the regolith apt repo is configured
  become: yes
  apt_repository:
    repo: deb https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy main
    state: present
    filename: regolith

- name: be sure regolith packages are installed
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400
    name:
      - acpi
      - i3xrocks-battery
      - regolith-desktop

- name: be sure unwanted packages are removed
  become: yes
  apt:
    state: absent
    name:
      - i3xrocks-cpu-usage
      - i3xrocks-net-traffic

- name: be sure the regolith config is linked
  file:
    src: ~/git/ansible-workstation/roles/regolith/files/home/config
    dest: ~/.config/regolith2
    state: link

- name: be sure the ~/.local/share/i3xrocks is linked
  file:
    src: ~/git/ansible-workstation/roles/regolith/files/home/local/share/i3xrocks
    dest: ~/.local/share/i3xrocks
    state: link
