---
- name: be sure podman is installed
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400
    name:
      - podman

- name: be sure docker →  podman link exists
  ansible.builtin.file:
    src: /usr/bin/podman
    dest: "/home/{{ workstation_user }}/.local/bin/docker"
    state: link

# - name: be sure unqualified registries are configured
#   become: yes
#   ansible.builtin.lineinfile:
#     path: /etc/containers/registries.conf
#     regexp: "unqualified-search-registries ="
#     line: 'unqualified-search-registries = ["docker.io"]'

- name: be sure podman-compose is installed
  community.general.pipx:
    name: podman-compose

- name: be sure the bash config is linked
  ansible.builtin.file:
    src: "~/git/ansible-workstation/roles/podman/files/podman.sh"
    dest: "~/.bashrc.d/podman.sh"
    state: link
    force: yes
