---
- name: be sure kitty is installed
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400
    name:
    - kitty

- name: be sure the kitty config is linked
  file:
    src: ~/git/ansible-workstation/roles/kitty/files/config
    dest: ~/.config/kitty
    state: link

- name: be sure kitty is the default terminal emulator
  become: yes
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/kitty
