---
- name: be sure /opt/kitty exists
  become: yes
  file:
    path: /opt/kitty
    state: directory

- name: stat kitty
  stat:
    path: /opt/kitty/bin/kitty
    checksum_algorithm: sha256
  register: kitty_result

- name: download the kitty archive
  get_url:
    url: https://github.com/kovidgoyal/kitty/releases/download/v0.25.0/kitty-0.25.0-x86_64.txz
    dest: /tmp/kitty-0.25.0-x86_64.txz
    checksum: "sha256:6a64e8a74acc35fd953b5554308685c724f87410e58e918281f95116ec09ad8f"
  when: kitty_result.stat.exists == False or kitty_result.stat.checksum != "91ac20a381229a5ab1cf4b6847311534d3d12b22f9e78dda32704410da4e4815"
  register: kitty_download

- name: extract kitty archive
  become: yes
  unarchive:
    src: /tmp/kitty-0.25.0-x86_64.txz
    dest: /opt/kitty
    remote_src: yes
  when: kitty_download.changed

- name: be sure kitty bin is linked
  become: yes
  file:
    src: /opt/kitty/bin/kitty
    dest: /usr/local/bin/kitty
    state: link

- name: be sure kitty-terminfo is installed
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400
    name:
      - kitty-terminfo

- name: be sure the kitty desktop files are linked
  file:
    src: "/opt/kitty/share/applications/{{ item }}.desktop"
    dest: "~/.local/share/applications/{{ item }}.desktop"
    state: link
  with_items:
  - kitty
  - kitty-open

- name: be sure the icons directories exists
  file:
    path: ~/.local/share/icons/hicolor/scalable/apps
    state: directory

- name: be sure the kitty icon is linked
  file:
    src: /opt/kitty/share/icons/hicolor/scalable/apps/kitty.svg
    dest: ~/.local/share/icons/hicolor/scalable/apps/kitty.svg
    state: link

- name: be sure the kitty config is linked
  file:
    src: ~/git/ansible-workstation/roles/kitty/files/config
    dest: ~/.config/kitty
    state: link

- name: be sure kitty is the default terminal emulator
  become: yes
  alternatives:
    name: x-terminal-emulator
    path: /opt/kitty/bin/kitty
