---
- name: be sure fzf is installed
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400
    name:
      - fzf

- name: be sure the fzf config is linked
  file:
    src: ~/git/ansible-workstation/roles/fzf/files/fzf.sh
    dest: ~/.bashrc.d/fzf.sh
    state: link
