---
- name: be sure the git files are linked
  file:
    src: "~/git/ansible-workstation/roles/git/files/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items:
    - .gitconfig
    - .gitignore
