---
- name: Test youtube-dl cheksum
  ansible.builtin.stat:
    path: ~/.local/bin/yt-dlp
    checksum_algorithm: sha256
  register: youtubedl_stat

- name: Be sure youtube-dl is installed
  ansible.builtin.get_url:
    url: https://github.com/yt-dlp/yt-dlp/releases/download/2023.03.04/yt-dlp
    dest: ~/.local/bin/yt-dlp
    checksum: "sha256:91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca"
    mode: "700"
  when: youtubedl_stat.stat.exists == False or youtubedl_stat.stat.checksum != "91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca"
