---
- name: be sure the secret vars are included
  ansible.builtin.include_vars: "../../../secrets/{{ item }}/vars.yml"
  with_items:
    - element
    - personal

- name: be sure the ttf-mscorefonts eula is accepted
  become: yes
  ansible.builtin.debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    vtype: boolean
    value: "true"

- name: be sure basic packages are installed
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400
    name:
      - aptitude
      - brightnessctl
      - cheese
      - curl
      - fuse3
      - gcc
      - gimp
      - gnupg2
      - gparted
      - htop
      - hunspell-de-de-frami
      - hunspell-en-gb
      - imagemagick
      - jq
      - make
      - net-tools
      - nmap
      - ntfs-3g
      - pavucontrol
      - python-is-python3
      - python3-psutil
      - simple-scan
      - ttf-mscorefonts-installer

- name: be sure packages are uninstalled
  become: yes
  ansible.builtin.apt:
    state: absent
    name:
      - brltty
      - wslu

- name: disable systemd-oomd
  become: yes
  ansible.builtin.systemd:
    name: systemd-oomd
    state: stopped
    masked: yes

- name: be sure sysctl is configured
  become: yes
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    fs.inotify.max_user_watches: 256000
    fs.inotify.max_user_instances: 512
