---
language: en-GB
dictionaries:
  - "de-de"
  - common
  - matrix
dictionaryDefinitions:
  - name: common
    path: common.txt
  - name: matrix
    path: matrix.txt
ignorePaths:
  - dist/**
  - node_modules/**
  - vendor/**
import:
  - "@cspell/dict-de-de/cspell-ext.json"
